---
title: Comparison Report
output: pdf_document
---
<!-- 
    This file is used to make it easier to resolve issues of accidentally collecting too few or too much data with the Sonde
-->

<!-- This chunk handles a bunch of pre-processing and won't display anything -->
```{r include=FALSE}
# Load libraries being used
library(readxl)
library(tibble)
library(dplyr)

# Adds a list of global variables into the current environment from 00_Globals.r
# This portion of the code assumes that you are in the root of the repository
# However, when knitr is used, it'll likely start a new R process who's working directory is the folder of current file
# - Root <- This is the root of the repository
#   - 01_Data
#     - MHK_Data
#       - ...
#   - 02_Scripts
#     - ...
#   - 03_Graphs
#     - ...
#   - 04_Rmarkdown <- Working directory of knitr process
#     - ...
#   - ...

if (basename(getwd()) == "04_Rmarkdown"){
  source(file.path("..", "02_Scripts", "00_Globals.r"))
} else {
  source(file.path("02_Scripts", "00_Globals.r"))
}

# Name of the file with errors
error_file_name <- paste0("Name of file here", ".csv")

# Constructs an OS agnostic path to the file
error_file_path <- file.path(KOR_FORMATTED_DATA_DIR, error_file_name)

# Ensure the file actually exists, else stop the execution of the program
if (!file.exists(error_file_path)) {
  stop(paste("The path '", error_file_path, "'' leads to nothing"))
}

# The file with the errors in it is loaded as a dataframe
error_df <- readr::read_csv(error_file_path)

# Checks to see if the file has 2024 or 2025 in its name and
# Then, chooses the correct DO sensor file to compare to
# NOTE: Any comments on the data are stored in the original files they came from (Minnewaska_FieldDataYYYY.xlsx)
if (grepl("2024", error_file_name)) {
  do_sensor_df <- read_xlsx(file.path(DO_SENSOR_DATA_DIR, "MHK_2024_DOSensor.xlsx"))
} else if (grepl("2025", error_file_name)) {
  do_sensor_df <- read_xlsx(file.path(DO_SENSOR_DATA_DIR, "MHK_2025_DOSensor.xlsx"))
}

# We only care about the data with the exact same date as the data in the error_df
# The date is converted to a date object so that it always follows the %m/%d/%Y format
error_df_date <- format(
  as.Date(error_df$Date[1], format = "%m/%d/%Y"),
  "%m/%d/%Y"
)

# Convert all of the dates in the do_sensor_df into strings
do_sensor_df$collect_date <- format(do_sensor_df$collect_date, "%m/%d/%Y")

# Added dplyr:: to tell the interpreter we're using dplyr::filter instead of stats::filter
do_sensor_df <- dplyr::filter(do_sensor_df, collect_date == error_df_date)
```

<!-- Begin the stuff that should be edited by the user -->
<!-- Every line with 5 #'s should be edited if desired -->

```{r include=FALSE}
# Stores the amount of rows in the error dataframe
error_df_row_count <- nrow(error_df)

# The expected amount of rows is 49 because we go from 0 to 12 meters and count every 0.25 meters
# The amount of extra or missing rows
extra_or_missing_rows_count <- 49 - error_df_row_count

is_extra <- extra_or_missing_rows_count < 0
is_missing <- extra_or_missing_rows_count > 0

# If we get a negative number,
# then the count should still be positive as it'll be a count for how many extra rows are there
extra_or_missing_rows_count <- abs(extra_or_missing_rows_count)

# These are the rows that are either removed or added to the error df
# When empty, rows are chosen randomly
rows_to_modify <- c() #####

# Choose rows randomly if empty
if (length(rows_to_modify) == 0) {
  # Choose n extra rows randomly
  rows_to_modify <- sample(1:nrow(error_df), extra_or_missing_rows_count)
}
```

<!-- Show the rows being modified -->

```{r}
paste0("The row(s) being modified are: ", paste(rows_to_modify, collapse = ", "))
```

<!-- Remove or Add the rows -->

```{r include=FALSE}
if (is_missing) {
  # If missing, add rows of NA at specified positions
  for (i in rows_to_modify) {
    # Added tibble:: to tell the interpreter that we're using the tibble library and not the dplyr library
    error_df <- tibble::add_row(error_df, .before = i)
  }
} else if (is_extra) {
  # If extra, delete rows from the rows_to_modify vector
  error_df <- error_df[-rows_to_modify, ]
}
```

<!-- Draw the graphs -->

# Draw Depth (m) vs Temperature (°C)
```{r}
# Depths vs Temperature Graph

depth_sonde <- seq(0, 12, 0.25)
temp_sonde <- error_df$temp_degC

temp_do_sensor <- do_sensor_df$Temp_C_DOProbe
# Not every dataset from the DO sensor ends at 12m, so that must be reflected here
depth_do_sensor <- 0:max(do_sensor_df$Depth_m)

# Start the creation of the plot
# The max and min points for each graph
max_depth <- max(depth_sonde, depth_do_sensor, na.rm = TRUE)
min_depth <- min(depth_sonde, depth_do_sensor, na.rm = TRUE)
max_temp <- max(temp_sonde, temp_do_sensor, na.rm = TRUE)
min_temp <- min(temp_sonde, temp_do_sensor, na.rm = TRUE)

# Draw the empty plot
plot(
  c(min_temp, max_temp),
  c(min_depth, max_depth),
  type = "n",
  xlab = "Temperature (°C)", ylab = "Depth (m)",
  main = "Depth (m) vs Temperature (°C)",
  xlim = c(max_temp, min_temp), # Invert the x-axis
  ylim = c(12, 0), # Invert the y-axis
  axes = FALSE # Don't draw the axes since we already draw them
)

# Draw the axes
# x-axis
axis(1, at = seq(min_temp, max_temp, 0.5))

# y-axis
axis(2, at = 12:0)

# Add the first graph
points(temp_sonde, depth_sonde, col = "red")

# Connect the points with lines
lines(temp_sonde, depth_sonde, col = "red")

# And draw the 2nd graph
# Start with the points
points(temp_do_sensor, depth_do_sensor, col = "blue")

# Then, connect them with lines
lines(temp_do_sensor, depth_do_sensor, col = "blue")

# Add a legend to the graph
legend(
  "bottomleft",
  inset = 0.05,
  legend = c("Sonde", "DO Sensor"),
  fill = c("red", "blue")
)
```


# Draw Depth (m) vs DO Saturation (%)
```{r}
# Depths vs DO Saturation Graph

do_sat_sonde <- error_df$doSaturation_percent

do_sat_do_sensor <- do_sensor_df$DO_Sat_Percent

# Start the creation of the plot
# The max and min points for each graph
max_do_sat <- max(do_sat_sonde, do_sat_do_sensor, na.rm = TRUE)
min_do_sat <- min(do_sat_sonde, do_sat_do_sensor, na.rm = TRUE)

# Draw the empty plot
plot(
  c(min_do_sat, max_do_sat),
  c(min_depth, max_depth),
  type = "n",
  xlab = "DO Saturation (%)", ylab = "Depth (m)",
  main = "Depth (m) vs DO Saturation (%)",
  xlim = c(max_do_sat, min_do_sat), # Invert the x-axis
  ylim = c(12, 0), # Invert the y-axis
  axes = FALSE # Don't draw the axes since we already draw them
)

# Draw the axes
# x-axis
axis(1, at = seq(min_do_sat, max_do_sat))

# y-axis
axis(2, at = 12:0)

# Add the first graph
points(do_sat_sonde, depth_sonde, col = "red")

# Connect the points with lines
lines(do_sat_sonde, depth_sonde, col = "red")

# And draw the 2nd graph
# Start with the points
points(do_sat_do_sensor, depth_do_sensor, col = "blue")

# Then, connect them with lines
lines(do_sat_do_sensor, depth_do_sensor, col = "blue")

# Add a legend to the graph
legend(
  "bottomleft",
  inset = 0.05,
  legend = c("Sonde", "DO Sensor"),
  fill = c("red", "blue")
)
```